### ISSUE TITLE
fromEvent is not an function in scrollService

### ISSUE THREAD

**Issue by inklingsofreality** [abhazelton/animate-on-scroll#15]
This issue popped up recently when we upgraded to the latest version.

Basically, this line in scroll.service.ts
`import { Observable, Subscription, fromEvent } from 'rxjs';`
needs to be changed to
```
   import { Observable, Subscription } from 'rxjs';
   import { fromEvent } from 'rxjs/observable/fromEvent';

```
I have a fix on my local machine. I was going to file the pull request, but don't have permissions, it seems.

**Comment by inklingsofreality** [comment]
I was able to submit the pull request.

**Comment by abhazelton** [comment]
Was working for me, but must be different in another version, I merged, thanks.
