### ISSUE TITLE
Delay start of animation

### ISSUE THREAD

**Issue by rafagsiqueira** [abhazelton/animate-on-scroll#17]
First of all thank you very much for this. 
If I may suggest the addition of an option to delay the start of the animation, similar to the offset attribute. 
This is useful when elements are positioned at the same scroll position but should be animated at different times.

**Comment by RayKimEX** [comment]
I think you can do with CSS property 'animation-delay'

**Comment by abhazelton** [comment]
Yeah, that's a CSS property, and better handled there.  You can see how I did the same thing on this page: https://solidknot.com/translation.  Thanks for the suggestion and glad you find the module useful!

**Comment by rafagsiqueira** [comment]
@abhazelton and @RayKimEX thank you for your help. I had tried using the css classes "delay-Xs" from animate.css and that did not work. With your solution however, it worked perfectly:
```
.animated-delay-1 {
    animation-delay: .15s;
    -webkit-animation-delay: .15s;
    -moz-animation-delay: .15s;
    -o-animation-delay: .15s
}
```
```
<div class="hide-on-init" animateOnScroll animationName="animated animated-delay-1 fadeInLeft">
```

**Comment by abhazelton** [comment]
no problem, glad it worked!
