### ISSUE TITLE
Can't resolve 'rxjs/observable/fromEvent'

### ISSUE THREAD

**Issue by borisdebusscher** [abhazelton/animate-on-scroll#20]
Can you please help me ? Thanks :)

./node_modules/ng2-animate-on-scroll/dist/src/scroll.service.js Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in 'myproject/node_modules/ng2-animate-on-scroll/dist/src'

**Comment by abhazelton** [comment]
See #15. This is a change in the rxjs package.  Upgrade rxjs to a more recent version and this should go away.

**Comment by borisdebusscher** [comment]
Great it works thanks! :)


On 23 October 2018 at 22:19:09, Aaron Hazelton (notifications@github.com)
wrote:

See #15 <https://github.com/abhazelton/animate-on-scroll/issues/15>. This
is a change in the rxjs package. Upgrade rxjs to a more recent version and
this should go away.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/abhazelton/animate-on-scroll/issues/20#issuecomment-432403671>,
or mute the thread
