### ISSUE TITLE
Adding attribute animateOnScroll conditionally

### ISSUE THREAD

**Issue by dhruveonmars** [abhazelton/animate-on-scroll#22]
When I use the following code
`<h2 animateOnScroll animationName="{{newsitems.length%2===1 && i===0 ? 'animated '+'fadeInUp' : null}}" class="sectiontitle" [class.hide-on-init]="newsitems.length%2===1 && i===0">{{newsitem.title}}</h2>` inside an *ngFor, the items display correctly and and animate correctly, however in the console I get the error `Error: animationName required` for each item that it fails to add a value to animationName.
I have tried to add the attribute animateOnScroll conditionally, with the following
`<h2 [attr.animateOnScroll]="newsitems.length%2===1 && i===0 ? '' : undefined" [attr.animationName]="newsitems.length%2===1 && i===0 ? 'animated '+'fadeInUp' : null" [class.hide-on-init]="newsitems.length%2===1 && i===0" class="sectiontitle">{{newsitem.title}}</h2>`
but that doesn't run the animation, as it doesn't trigger adding the relevant classes.

It works if I do the following;
`<h2 animateOnScroll animationName="{{newsitems.length%2===1 && i===0 ? 'animated '+'fadeInUp' : 'null'}}" class="sectiontitle" [class.hide-on-init]="newsitems.length%2===1 && i===0">{{newsitem.title}}</h2>`
although, I don't think using an irrelevant class such as `null` is really the right way to go about it.

Any help with this is appreciated

**Comment by abhazelton** [comment]
As you may have noticed, there hasn't been any updates in a while on this.  I'm too busy to keep up with it and haven't been working on any Angular projects for a while, so if someone wants to take this over, you are welcome to it.
