### ISSUE TITLE
Lazy Modules

### ISSUE THREAD

**Issue by clegeard** [abhazelton/animate-on-scroll#24]
Hi,
I am trying to use your module in an app which is using lazy modules, but without success.
Is there something particular I should do in that case?
Thanks

**Comment by clegeard** [comment]
I forgot to mention my project is Angular 7

**Comment by abhazelton** [comment]
As you may have noticed, there hasn't been any updates in a while on this.  I'm too busy to keep up with it and haven't been working on any Angular projects for a while, so if someone wants to take this over, you are welcome to it.

**Comment by bufke** [comment]
Cleaning up issues, I use this project with lazy loaded modules without a problem. I use the `    AnimateOnScrollModule.forRoot()` in my app.module. I don't add the forRoot in feature modules.
