### ISSUE TITLE
Can't resolve 'rxjs/observable/fromEvent' still occurs without rxjs-compat

### ISSUE THREAD

**Issue by bufke** [abhazelton/animate-on-scroll#25]
Related to #20 and #21 

It seems like there is still an issue. Using rxjs 6.5.2. This library won't work without also adding rxjs-compat. It seems like the other tickets suggest that rxjs-compat is not required and that updating rxjs fixes the issue. However I find that not to be the case.

```
ERROR in ./node_modules/ng2-animate-on-scroll/dist/src/scroll.service.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in 'node_modules/ng2-animate-on-scroll/dist/src'
```

The issue I believe is [here](https://github.com/abhazelton/animate-on-scroll/blob/master/src/scroll.service.ts#L3) 

`import { fromEvent } from 'rxjs/observable/fromEvent';`

should be 

`import { fromEvent } from 'rxjs';`

**Comment by abhazelton** [comment]
As you may have noticed, there hasn't been any updates in a while on this.  I'm too busy to keep up with it and haven't been working on any Angular projects for a while, so if someone wants to take this over, you are welcome to it.

**Comment by bufke** [comment]
Understandable. Would you mind adding me to npm and this project in that case? Would you mind if I add a co-worker as well? My npm username is also `bufke`.

Feel free to review my history on github and [gitlab](https://gitlab.com/bufke). The agency's open source work is [here](https://gitlab.com/thelabnyc)

**Comment by abhazelton** [comment]
@bufke Sure thing, that would be great.  I hated to drop everyone since it seemed to be pretty useful, but it needs to be updated to keep up with new releases and such and I've only been working on React projects for a while now, so I'm getting out of the loop.

**Comment by abhazelton** [comment]
Just added you to both.  Let me know if you have any issues with that.
