### ISSUE TITLE
Doesn't work with Angular 9

### ISSUE THREAD

**Issue by edward24689** [abhazelton/animate-on-scroll#33]
ERROR in Symbol AnimateOnScrollDirective declared in /Users/my-project/node_modules/ng2-animate-on-scroll/dist/src/animate-on-scroll.directive.js is not exported from /Users/my-project/node_modules/ng2-animate-on-scroll/dist/src/animate-on-scroll (import into /Users/my-project/node_modules/ng2-animate-on-scroll/dist/index.js)

**Comment by bufke** [comment]
Yeah I saw this too even after work to make it ivy compatible. I suspect it's something related to the packaging. I was considering solving this by setting up angular-cli's library project structure. All the other Angular stuff I manage uses that. 

As a poor workaround - if you copy the files manually into your Angular 9 project it should work.

**Comment by abhazelton** [comment]
@bufke would you like me to transfer ownership of this repo to you?

**Comment by bufke** [comment]
I'm fine with that if you'd rather do so. I doubt I'll really do any more feature dev here but I'm happy to keep it running.

**Comment by abhazelton** [comment]
Still getting a fair amount of weekly downloads, so if possible, would be good to at least maintain it, but I'm not able to anymore.

**Comment by bufke** [comment]
This was fixed awhile ago but I think we forgot to tag the release. @JNaftali can you write up release notes.
