### ISSUE TITLE
Offset property now working

### ISSUE THREAD

**Issue by Josee9988** [abhazelton/animate-on-scroll#36]
The animation starts at the same PX even though I set the default offset (80) or I set a super high number such as 8000.

It simply shows no change between 80 and 8000.

```html
<img animateOnScroll animationName="animated shake" class="hide-on-init" offset="8000" src="../../../../assets/images/main-descr-people-looking-pc.png"
         alt="gente buscando información en un ordenador">
```

**Comment by OpticNectar** [comment]
@Josee9988 I had the same issue, but it turned out to be animate.css uses different classes now. They use `animate__animated` and `animate__fadeIn` etc.

**Comment by Josee9988** [comment]
> @Josee9988 I had the same issue, but it turned out to be animate.css uses different classes now. They use `animate__animated` and `animate__fadeIn` etc.

Maybe that's the problem

**Comment by OswaldoChacon** [comment]
i am using animate.css and offset, but not workings.
there isn't differente if use or not.

I tried it with my custom css but was unsuccessful

what happen?

**Comment by Abhirup-99** [comment]
You should use threshold, offset won't help with Intersection observer. Either use threshold or set useScroll.

**Comment by OswaldoChacon** [comment]
sorry, the last time not tried with theshold but now i tried and works
