### ISSUE TITLE
Angular 11 Support

### ISSUE THREAD

**Issue by daverickdunn** [abhazelton/animate-on-scroll#53]
NPM dependency error when using `"@angular/common": "~11.1.0"` , see below:

Note, this may in part be due to the NPM version, I believe the latest versions are stricter.

- Node: 15.6.0
- NPM: 7.4.0

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^9.0.2" from ng2-animate-on-scroll@2.2.0
npm ERR! node_modules/ng2-animate-on-scroll
npm ERR!   ng2-animate-on-scroll@"*" from the root project
```

**Comment by Abhirup-99** [comment]
use the latest version, it's updated.

**Comment by daverickdunn** [comment]
I am.

**Comment by Abhirup-99** [comment]
Thanks for reporting the bug, a fix would be pushed shortly.

**Comment by Abhirup-99** [comment]
A version has been released, please take a look.

**Comment by daverickdunn** [comment]
Still the same issue for me as I'm on `11.1.0` and your peer dependency is set to `~11.0.7` (i.e. only _patches_ can vary).

You need to use `^` rather than `~` for it to be compatible with all `11.x.x` releases.

I suggest setting your peer dependencies to:

```json
"peerDependencies": {
  "@angular/common": "^11.0.0",
  "@angular/core": "^11.0.0"
}
```

**Comment by Abhirup-99** [comment]
Can you pull back your version, as we won't be making another release before some time.

**Comment by daverickdunn** [comment]
Haha, no chance! I've been using `npm i -f` since before opening this issue, so it's not a problem for me. I only opened it for your benefit; new users who can't install the package will simply move on. 

I'm kind of curious though, why the hesitation to release? It's a simple fix.
