### ISSUE TITLE
error when use offset

### ISSUE THREAD

**Issue by OswaldoChacon** [abhazelton/animate-on-scroll#54]
i want use offset but i has an error, the error say: 'Type 'string' is not assignable to type 'number'.

i'am following the instructions in the documentation, but not have sucess.

I understand the error, however not can't fix it

**Comment by Abhirup-99** [comment]
Are you using scroll Listener or intersection observer.

**Comment by OswaldoChacon** [comment]
Not really.

I am using the next code:


​<​div​ ​animateOnScroll​ ​animationName​="​animated slideDown​" ​offset​="​120​"​>​
    content with different pixel offset specified
  ​</​div​>

This example is in the documentation. Without 'offset' works well, but i need use offset.


PD: Sorry for my english, it is not my native language

**Comment by Abhirup-99** [comment]
Use threshold, offset is for scroll Listener. Threshold is for intersection observer implementation.

**Comment by Abhirup-99** [comment]
> i want use offset but i has an error, the error say: 'Type 'string' is not assignable to type 'number'.
> 
> i'am following the instructions in the documentation, but not have sucess.
> 
> I understand the error, however not can't fix it

Can you share a screenshot of the error message, just tried it. Seemed to work well.

**Comment by OswaldoChacon** [comment]
<img width="386" alt="error ng2" src="https://user-images.githubusercontent.com/39079647/106766499-8c4f3880-65ff-11eb-91d2-5f0966fa9ec0.png">
<img width="639" alt="error ng2-2" src="https://user-images.githubusercontent.com/39079647/106766571-9ec97200-65ff-11eb-8b7e-b1fb1629db0e.png">



> > i want use offset but i has an error, the error say: 'Type 'string' is not assignable to type 'number'.
> > i'am following the instructions in the documentation, but not have sucess.
> > I understand the error, however not can't fix it
> 
> Can you share a screenshot of the error message, just tried it. Seemed to work well.

**Comment by OswaldoChacon** [comment]
> > i want use offset but i has an error, the error say: 'Type 'string' is not assignable to type 'number'.
> > i'am following the instructions in the documentation, but not have sucess.
> > I understand the error, however not can't fix it
> 
> Can you share a screenshot of the error message, just tried it. Seemed to work well.

<img width="364" alt="error ng2" src="https://user-images.githubusercontent.com/39079647/106766827-db956900-65ff-11eb-9aa4-8abda0ab4974.png">
<img width="639" alt="error ng2-2" src="https://user-images.githubusercontent.com/39079647/106766840-df28f000-65ff-11eb-9ec0-c61880410719.png">

**Comment by OswaldoChacon** [comment]
> > i want use offset but i has an error, the error say: 'Type 'string' is not assignable to type 'number'.

<img width="364" alt="error ng2" src="https://user-images.githubusercontent.com/39079647/106767026-126b7f00-6600-11eb-9563-bcc4abe6f965.png">
<img width="646" alt="error ng2-2" src="https://user-images.githubusercontent.com/39079647/106767032-14354280-6600-11eb-84b8-885782614968.png">

**Comment by Abhirup-99** [comment]
Use this [offset]=120, I would update the example. Also, if you are not using useScroll, it would be better to use threshold,
[threshold]=123.

**Comment by OswaldoChacon** [comment]
thank you very much, the problem was fixed it
