### ISSUE TITLE
import { AnimateOnScrollModule } from 'ng2-animate-on-scroll';

### ISSUE THREAD

**Issue by physedo** [abhazelton/animate-on-scroll#58]
version 2.3.0
cannot fin module 'ng2-animate-on-scroll' and its type declarations 
when I : npm i ng2-animate-on-scroll

**Comment by Abhirup-99** [comment]
Can you try now, published another version.

**Comment by Abhirup-99** [comment]
I just installed it with both old and new version.

**Comment by chris480** [comment]
facing same issue on 2.3.1 
Currently on A11

**Comment by Abhirup-99** [comment]
![test](https://user-images.githubusercontent.com/48902681/135565793-e3115070-be36-4a62-a1d1-f634adc431f7.PNG)

**Comment by Abhirup-99** [comment]
Can you detail the env you are running in?

**Comment by physedo** [comment]
Same issue

**Comment by Abhirup-99** [comment]
2.3.0 is for angular 12. For 11, use 2.2.1

**Comment by Abhirup-99** [comment]
I would try bringing the versions in sync with the angular versions from the next release.

**Comment by physedo** [comment]
angular 12.2.7

**Comment by Abhirup-99** [comment]
@physedo @chris480 just asking did this get fixed?

**Comment by physedo** [comment]
no

**Comment by Abhirup-99** [comment]
Can you try once more? Published a new version. Hopefully would be fixed now.

**Comment by physedo** [comment]
@Abhirup-99 It works now. But not animating on Scroll. It is  a directive? do you need that animate.css?

**Comment by Abhirup-99** [comment]
Yes, it's a directive. And the animations have to be provided by you. The library is a wrapper for intersection observer/scroll listener. Check out the stackbiltz examples/ the example angular app in the code itself.

**Comment by physedo** [comment]
@Abhirup-99 thank you
