### ISSUE TITLE
"Animate on scroll" feature doesn't work when viewing a minimized viewport

### ISSUE THREAD

**Issue by Bidthedog** [abhazelton/animate-on-scroll#7]
Issue 1: When working in Chrome, with developer tools turned on, or on a desktop with a resized window, the "on scoll" part doesn't work - i.e. the animation works, but it seems to animate either immediately (on load), or at a unexpected scroll point on the screen. This also affects the "offset" feature - can't quite seem to get this working.

Looking into this a bit further, it seems that `this.winHeight = window.screen.height` might be the root of the issue. Suggest changing this to `window.innerHeight` to capture the actual height of the viewport, rather than the window height. There might be other code that needs changing in relation to this.

Issue 2: May be related, but all elements seem to be visible initially, and when the animation kicks in they disappear, then animate in.

Going to look at both these issues in a PR - leave it with me.

**Comment by Bidthedog** [comment]
See PR #8

**Comment by abhazelton** [comment]
Thanks @Bidthedog
